from AutoLayout.settings import *

MAINBED_MAX_LEN = 5500
MAINBED_MIN_LEN = 2800

# 躺椅相关
MAINBED_RECLINERS_THRE_DIS = 4000
MAINBED_RECLINERS_THRE_AREA = 4000*4000#只有大于等于4000*4000的房子才能放置躺椅
MAINBED_RECLINERS_DIS_BED = 300     # 床椅距离
MAINBED_RECLINERS_FAR_DIS = 600     # 椅跟床偏置距离

MAINBED_BED_LEN = 2100
MAINBED_BED_WIDTH = (1500, 1800)

#
RANGE_LEN =(max(MAINBED_BED_WIDTH)+min(BEDSIDE_NIGHTTABLE_WIDTH),
            min(MAINBED_BED_WIDTH)+min(BEDSIDE_NIGHTTABLE_WIDTH))

# 床，床头柜，躺椅组合
MAINBED_BED_RECLINERS_LEN_DIFF = 0
MAINBED_COMBINED_BED_RECLINERS_LEN = MAINBED_BED_LEN + MAINBED_BED_RECLINERS_LEN_DIFF # 躺椅在床的方向上多出 0 mm
MAINBED_COMBINED_BED_RECLINERS_WIDTH = []
MAINBED_COMBINED_BED_RECLINERS_BEDSIZE = []
MAINBED_COMBINED_BED_RECLINERS_TABLESIZE = []
MAINBED_COMBINED_BED_NO_RECLINERS_LEN = MAINBED_BED_LEN
MAINBED_COMBINED_BED_NO_RECLINERS_WIDTH = []
MAINBED_COMBINED_BED_NO_RECLINERS_BEDSIZE = []
MAINBED_COMBINED_BED_NO_RECLINERS_TABLESIZE = []

# 躺椅距离床边 300 mm
for b in MAINBED_BED_WIDTH:
    for bt in BEDSIDE_NIGHTTABLE_WIDTH:
        MAINBED_COMBINED_BED_RECLINERS_WIDTH.append(b + bt + \
                    MAINBED_RECLINERS_DIS_BED + RECLINERS_WIDTH_LEN[0])
        MAINBED_COMBINED_BED_RECLINERS_BEDSIZE.append(b)
        MAINBED_COMBINED_BED_RECLINERS_TABLESIZE.append(bt)

        MAINBED_COMBINED_BED_NO_RECLINERS_WIDTH.append(b+bt+bt)
        MAINBED_COMBINED_BED_NO_RECLINERS_BEDSIZE.append(b)
        MAINBED_COMBINED_BED_NO_RECLINERS_TABLESIZE.append(bt)

# 床尾过道最小距离
MAINBED_BED_END_THRE_DIS = 500







